"""
Simple helper program to create five output text files that follow the
naming convention used in the research-helper project.

Usage:
    python build_output_files.py <base_name>

If <base_name> is omitted, the program will prompt for it.
"""

from __future__ import annotations

import sys
from pathlib import Path


SUFFIXES = [
    "_AC_ouput.txt",
    "_C&W_output.txt",
    "_CPLEX_output.txt",
    "_GA_ouput.txt",
    "_H_output.txt",
]


def create_files(base_name: str) -> None:
    """
    Create the five text files using the provided base name.
    """
    project_root = Path(__file__).resolve().parent

    for suffix in SUFFIXES:
        filename = f"{base_name}{suffix}"
        file_path = project_root / filename

        if file_path.exists():
            print(f"Skipping existing file: {filename}")
            continue

        file_path.write_text(
            f"{filename}\nGenerated by build_output_files.py\n",
            encoding="utf-8",
        )
        print(f"Created: {filename}")


def main() -> None:
    """
    Entry point: accept the base name via CLI argument or prompt.
    """
    if len(sys.argv) > 1:
        base_name = sys.argv[1].strip()
    else:
        base_name = input("Enter base name: ").strip()

    if not base_name:
        print("Base name cannot be empty.")
        sys.exit(1)

    create_files(base_name)


if __name__ == "__main__":
    main()

